# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x10kariyernet.agent\"6\n\x10\x41nalyzeCvRequest\x12\x0f\n\x07\x63v_file\x18\x01 \x01(\x0c\x12\x11\n\tmime_type\x18\x02 \x01(\t\"c\n\x11\x41nalyzeCvResponse\x12\x0e\n\x06skills\x18\x01 \x03(\t\x12\x18\n\x10\x65xperience_level\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\x13\n\x0bsuggestions\x18\x04 \x03(\t\"x\n\x0cMatchRequest\x12\x0f\n\x07\x63v_file\x18\x01 \x01(\x0c\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x11\n\tjob_title\x18\x03 \x01(\t\x12\x17\n\x0fjob_description\x18\x04 \x01(\t\x12\x18\n\x10job_requirements\x18\x05 \x01(\t\"\x91\x01\n\rMatchResponse\x12\x1b\n\x13\x63ompatibility_score\x18\x01 \x01(\x05\x12\x13\n\x0b\x65xplanation\x18\x02 \x01(\t\x12\x1d\n\x15\x63\x61ndidate_explanation\x18\x03 \x01(\t\x12\x17\n\x0fmatching_skills\x18\x04 \x03(\t\x12\x16\n\x0emissing_skills\x18\x05 \x03(\t2\xbc\x01\n\x0c\x41gentService\x12T\n\tAnalyzeCv\x12\".kariyernet.agent.AnalyzeCvRequest\x1a#.kariyernet.agent.AnalyzeCvResponse\x12V\n\x13MatchCandidateToJob\x12\x1e.kariyernet.agent.MatchRequest\x1a\x1f.kariyernet.agent.MatchResponseB\x18\xaa\x02\x15KariyerNet.Agent.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\025KariyerNet.Agent.Grpc'
  _globals['_ANALYZECVREQUEST']._serialized_start=33
  _globals['_ANALYZECVREQUEST']._serialized_end=87
  _globals['_ANALYZECVRESPONSE']._serialized_start=89
  _globals['_ANALYZECVRESPONSE']._serialized_end=188
  _globals['_MATCHREQUEST']._serialized_start=190
  _globals['_MATCHREQUEST']._serialized_end=310
  _globals['_MATCHRESPONSE']._serialized_start=313
  _globals['_MATCHRESPONSE']._serialized_end=458
  _globals['_AGENTSERVICE']._serialized_start=461
  _globals['_AGENTSERVICE']._serialized_end=649
# @@protoc_insertion_point(module_scope)
